//! `bfb serverless query` — route searches across existing collections.
//!
//! Requests are generated by the same [`ConfigSearchGenerator`] as
//! `bfb search`, either from a search YAML (`--file` / `--example`) or from a
//! template derived from a matching collection's vector config. Each request
//! picks a collection according to `--distribution` and sends
//! `--search-batch-size` queries to it; the run itself (parallelism, `--rps`,
//! stats, `--jsonl-*`, `--json`) is driven by the shared [`process`] loop.

use std::sync::Arc;
use std::sync::Mutex;
use std::sync::atomic::{AtomicBool, Ordering};
use std::time::Instant;

use anyhow::{Context, Result, bail};
use indicatif::ProgressBar;
use qdrant_client::qdrant::{
    IdfParamsBuilder, Query, QueryBatchPointsBuilder, QueryPointsBuilder, SearchParamsBuilder,
    VectorInput,
};
use qdrant_client::serverless::{CollectionConfig, QdrantServerless};

use super::args::ServerlessQueryArgs;
use super::client::create_clients;
use super::collections::list_matching;
use super::distribution::CollectionPicker;
use crate::args::Args;
use crate::client::retry_with_clients;
use crate::config::examples::{ExampleKind, resolve};
use crate::config::search::{SearchCollectionConfig, SearchConfig, SearchRequestConfig};
use crate::config::{DatatypeKind, SparseSource, VectorSource};
use crate::generators::ConfigSearchGenerator;
use crate::generators::queries::GeneratedQuery;
use crate::processor::{Processor, Timing};
use crate::results::BenchmarkResults;
use crate::stats::process;

#[derive(Default)]
struct QueryStats {
    server_timings: Vec<Timing>,
    full_timings: Vec<Timing>,
    qps: Vec<Timing>,
    rps: Vec<Timing>,
}

struct ServerlessQueryProcessor {
    args: Args,
    stopped: Arc<AtomicBool>,
    clients: Vec<QdrantServerless>,
    names: Vec<String>,
    picker: CollectionPicker,
    generator: ConfigSearchGenerator,
    start_timestamp_millis: f64,
    start_time: Instant,
    stats: Mutex<QueryStats>,
}

impl ServerlessQueryProcessor {
    fn build_query(
        &self,
        generated: GeneratedQuery,
        collection: &str,
    ) -> Result<QueryPointsBuilder> {
        let (vector, using) = if let Some((values, indices, name)) = generated.sparse {
            (VectorInput::new_sparse(indices.data, values), Some(name))
        } else if let Some((values, name)) = generated.dense {
            (VectorInput::new_dense(values), name)
        } else {
            bail!("search config request must produce a dense or sparse vector");
        };

        let mut params = SearchParamsBuilder::default().exact(self.args.search_exact);
        if let Some(hnsw_ef) = self.args.search_hnsw_ef {
            params = params.hnsw_ef(hnsw_ef as u64);
        }
        if let Some(corpus) = generated.idf_corpus {
            params = params.idf(IdfParamsBuilder::default().corpus(corpus));
        }

        let mut builder = QueryPointsBuilder::new(collection)
            .query(Query::new_nearest(vector))
            .params(params)
            .limit(self.args.search_limit as u64)
            .with_payload(self.args.search_with_payload)
            .with_vectors(self.args.search_with_vectors);
        if let Some(name) = using.filter(|n| !n.is_empty()) {
            builder = builder.using(name);
        }
        if let Some(filter) = generated.filter {
            builder = builder.filter(filter);
        }
        Ok(builder)
    }

    async fn search(&self, req_id: usize, progress_bar: &ProgressBar) -> Result<()> {
        if self.stopped.load(Ordering::Relaxed) {
            return Ok(());
        }

        let mut rng = rand::rng();
        let collection = &self.names[self.picker.pick(&mut rng)];
        let template_idx = self.generator.random_template_idx(&mut rng);

        let queries = (0..self.args.search_batch_size)
            .map(|_| {
                let generated = self
                    .generator
                    .make_query_for(template_idx, req_id, &mut rng);
                self.build_query(generated, collection).map(|b| b.build())
            })
            .collect::<Result<Vec<_>>>()?;

        let mut request = QueryBatchPointsBuilder::new(collection, queries);
        if let Some(timeout) = self.args.timeout {
            request = request.timeout(timeout as u64);
        }
        let request = request.build();

        let start = Instant::now();
        let res = retry_with_clients(&self.clients, &self.args, |c| {
            c.query_batch(request.clone())
        })
        .await
        .with_context(|| format!("query on {collection}"))?;
        let elapsed = start.elapsed().as_secs_f32();
        let delay_millis = self.start_time.elapsed().as_millis() as u32;

        if res.time > self.args.timing_threshold {
            progress_bar.println(format!("Slow query on {collection}: {:?}", res.time));
        }

        let mut stats = self.stats.lock().unwrap();
        stats.server_timings.push(Timing {
            delay_millis,
            value: res.time as f32,
        });
        stats.full_timings.push(Timing {
            delay_millis,
            value: elapsed,
        });
        stats.qps.push(Timing {
            delay_millis,
            value: progress_bar.per_sec() as f32,
        });
        stats.rps.push(Timing {
            delay_millis,
            value: (progress_bar.per_sec() / self.args.search_batch_size as f64) as f32,
        });
        Ok(())
    }
}

impl Processor for ServerlessQueryProcessor {
    async fn make_request(
        &self,
        req_id: usize,
        _args: &Args,
        progress_bar: &ProgressBar,
    ) -> Result<()> {
        self.search(req_id, progress_bar).await
    }

    fn start_timestamp_millis(&self) -> f64 {
        self.start_timestamp_millis
    }

    fn server_timings(&self) -> Vec<Timing> {
        self.stats.lock().unwrap().server_timings.clone()
    }

    fn qps(&self) -> Vec<Timing> {
        self.stats.lock().unwrap().qps.clone()
    }

    fn rps(&self) -> Vec<Timing> {
        self.stats.lock().unwrap().rps.clone()
    }

    fn full_timings(&self) -> Vec<Timing> {
        self.stats.lock().unwrap().full_timings.clone()
    }

    fn get_batch_size(&self) -> usize {
        self.args.search_batch_size
    }
}

/// Derive a search config from a live collection: one random-query template
/// per dense and sparse vector, no filters.
fn infer_search_config(name: &str, config: &CollectionConfig) -> Result<SearchConfig> {
    let mut requests = Vec::new();

    let mut dense: Vec<_> = config.dense_vectors.iter().collect();
    dense.sort_by(|a, b| a.0.cmp(b.0));
    for (vector, cfg) in dense {
        requests.push(SearchRequestConfig::Dense {
            using: Some(vector.clone()).filter(|n| !n.is_empty()),
            size: cfg.size,
            datatype: DatatypeKind::default(),
            source: VectorSource::Random,
            filters: Vec::new(),
        });
    }

    let mut sparse: Vec<_> = config.sparse_vectors.keys().collect();
    sparse.sort();
    for vector in sparse {
        requests.push(SearchRequestConfig::Sparse {
            using: vector.clone(),
            source: SparseSource::default(),
            filters: Vec::new(),
            idf_corpus: Vec::new(),
        });
    }

    if requests.is_empty() {
        bail!("collection {name} has no vectors to query");
    }
    Ok(SearchConfig {
        collection: SearchCollectionConfig {
            name: name.to_string(),
        },
        requests,
    })
}

async fn fetch_config(client: &QdrantServerless, name: &str) -> Result<CollectionConfig> {
    let info = client
        .get_collection(name)
        .await
        .with_context(|| format!("get_collection {name}"))?;
    if !info.exists {
        bail!("collection {name} no longer exists");
    }
    info.config.ok_or_else(|| {
        anyhow::anyhow!("collection {name} has no config; re-upload or pass a search config")
    })
}

pub async fn run(args: &Args, query: ServerlessQueryArgs, stopped: Arc<AtomicBool>) -> Result<()> {
    let clients = create_clients(args)?;
    let summaries = list_matching(&clients[0], &query.collection_prefix).await?;
    if summaries.is_empty() {
        bail!(
            "no collections matched prefix {:?} — run `bfb serverless upload` first",
            query.collection_prefix
        );
    }

    let (names, empty): (Vec<_>, Vec<_>) = summaries
        .into_iter()
        .partition(|c| c.point_count != Some(0));
    let names: Vec<String> = names.into_iter().map(|c| c.collection_name).collect();
    if !empty.is_empty() {
        println!(
            "Skipping {} empty collection(s) matching the prefix",
            empty.len()
        );
    }
    if names.is_empty() {
        bail!(
            "every collection matching prefix {:?} is empty — run `bfb serverless upload` first",
            query.collection_prefix
        );
    }

    println!(
        "Querying {} collection(s) with prefix {:?} ({:?})",
        names.len(),
        query.collection_prefix,
        query.distribution
    );

    let (search_config, origin) = if query.config.is_some() {
        let resolved = resolve(
            query.config.file.as_deref(),
            query.config.example.as_deref(),
            ExampleKind::Search,
        )?;
        let config = crate::config::search::parse(&resolved.yaml, &resolved.origin)?;
        (config, Some(resolved.origin))
    } else {
        let config = fetch_config(&clients[0], &names[0]).await?;
        println!(
            "No search config given; deriving query shape from {}",
            names[0]
        );
        (infer_search_config(&names[0], &config)?, None)
    };

    let mut args = args.clone();
    args.collection_name = format!("{}*", query.collection_prefix);
    let mut results = BenchmarkResults::new(&args, origin);

    let processor = ServerlessQueryProcessor {
        args: args.clone(),
        stopped: stopped.clone(),
        clients,
        picker: CollectionPicker::new(names.len(), query.distribution.into())?,
        names,
        generator: ConfigSearchGenerator::new(&search_config)?,
        start_timestamp_millis: std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_millis() as f64,
        start_time: Instant::now(),
        stats: Mutex::new(QueryStats::default()),
    };

    results.results.search = Some(process(&args, stopped, processor).await?);
    results.write_if_requested(&args)
}

#[cfg(test)]
mod tests {
    use super::*;
    use qdrant_client::serverless::{DenseVectorConfig, Distance, SparseVectorConfig};

    #[test]
    fn infers_one_template_per_vector() {
        let config = CollectionConfig::new()
            .dense_vector(DenseVectorConfig::new(64, Distance::Dot))
            .named_dense_vector("image", DenseVectorConfig::new(512, Distance::Cosine))
            .named_sparse_vector("text", SparseVectorConfig::new());
        let search = infer_search_config("c", &config).unwrap();
        assert_eq!(search.collection.name, "c");
        assert_eq!(search.requests.len(), 3);
        match &search.requests[0] {
            SearchRequestConfig::Dense { using, size, .. } => {
                assert_eq!(using.as_deref(), None);
                assert_eq!(*size, 64);
            }
            other => panic!("unexpected {other:?}"),
        }
        match &search.requests[1] {
            SearchRequestConfig::Dense { using, size, .. } => {
                assert_eq!(using.as_deref(), Some("image"));
                assert_eq!(*size, 512);
            }
            other => panic!("unexpected {other:?}"),
        }
        assert!(
            matches!(&search.requests[2], SearchRequestConfig::Sparse { using, .. } if using == "text")
        );
    }

    #[test]
    fn vectorless_collection_is_rejected() {
        assert!(infer_search_config("c", &CollectionConfig::new()).is_err());
    }
}
