[package]
name = "bfb"
version = "1.9.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.98"
chrono = { version = "0.4.41", default-features = false, features = [
    "now",
    "std",
] }
clap = { version = "4.5.40", features = ["derive", "suggestions"] }
clap_autocomplete = "0.4.2"
ctrlc = "3.4.7"
futures = "0.3.31"
indicatif = "0.17.11"
memmap2 = "0.9.5"
qdrant-client = { git = "https://github.com/qdrant/rust-client", branch = "dev" }
rand = "0.9.1"
rand_distr = "0.5.1"
serde = "1.0"
serde_json = "1.0"
tokio = { version = "1.45.1", features = ["full"] }
tokio-stream = "0.1.17"
uuid = { version = "1.17.0", features = ["serde", "v4"] }
env_logger = "0.11.8"
indicatif-log-bridge = "0.2.3"
tracing = { version = "0.1.41", features = ["log"] }
